# Development override for docker-compose
# Use: docker-compose -f docker-compose.yml -f docker-compose.override.yml up

services:
  backend:
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=true
      - LOG_LEVEL=DEBUG
    volumes:
      - ./backend:/app
      - /app/__pycache__
    command: ["python", "run.py"]
    
  frontend:
    environment:
      - NODE_ENV=development
      - FAST_REFRESH=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: ["npm", "run", "dev"]
